# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/google-ads-test',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/google-ads-test',
                'lib_path': 'google_ads_test'},
  'syms': {'google_ads_test.core': {'google_ads_test.core.foo': ('core.html#foo', 'google_ads_test/core.py')}}}
